#!/bin/bash

echo -n "Building lists ..."
for i in `ls -1 IMG*`; 
do 
	STAT=`stat $i | grep Modify | sed -e 's/^Modify: //' -e 's/\..*$//' -e 's/ /_/'`;
	YYYYMM=`echo $STAT | sed -e 's/-[0-9]\{2\}_.*//'`
	echo "$i,$STAT" >> $YYYYMM.files; 
	echo $i >> $YYYYMM.manifest; 
	echo "$YYYYMM.files" >> $YYYYMM.manifest;
	cat $YYYYMM.manifest | sort | uniq > x;
	mv x $YYYYMM.manifest;
done
echo " ... Done"
echo "Making tarfiles"
for i in `ls -1 *.manifest`
do
	YYYYMM=`echo $i | sed -e 's/\..*$//'`
	echo "Making: $YYYYMM.tar.gz"
	tar czvf $YYYYMM.tar.gz -T $YYYYMM.manifest
done 
echo "Cleaning up ... "
rm *.files *.manifest
echo Done
